services:
  - type: web
    name: signspeak-server
    env: node
    rootDir: video-call/server
    buildCommand: rm -rf node_modules package-lock.json && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20