services:
  - type: web
    name: signspeak-server
    env: node
    rootDir: video-call/server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
